
ARG NODE_VERSION=24.7.0-alpine

# Use a lightweight Node.js image for building (customizable via ARG)
FROM node:${NODE_VERSION} AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package-related files first to leverage Docker's caching mechanism
COPY package.json package-lock.json ./

RUN npm ci --omit=dev

# Copy the rest of the application source code into the container
COPY . .

EXPOSE 3000

CMD ["node", "./server.js"]

